from application.data_transfer_object.home_automation.sensor.presence_sensor.create_presence_sensor.CreatePresenceSensorRequest import CreatePresenceSensorRequest
from application.data_transfer_object.home_automation.sensor.presence_sensor.create_presence_sensor.CreatePresenceSensorResponse import CreatePresenceSensorResponse
from application.data_transfer_object.home_automation.sensor.presence_sensor.patch_presence_sensor_data.PatchPresenceSensorDataRequest import PatchPresenceSensorDataRequest
from application.data_transfer_object.home_automation.sensor.presence_sensor.patch_presence_sensor_data.PatchPresenceSensorDataResponse import PatchPresenceSensorDataResponse
from application.interface.application.IPresenceSensorApplication import IPresenceSensorApplication
from application.interface.repository.IPresenceSensorRepository import IPresenceSensorRepository

class PresenceSensorApplication(IPresenceSensorApplication):

    def __init__(self, presenceSensorRepository: IPresenceSensorRepository):
        self._presenceSensorRepository = presenceSensorRepository

    async def CreatePresenceSensor(self, createPresenceSensorRequest: CreatePresenceSensorRequest) -> CreatePresenceSensorResponse:
        return await self._presenceSensorRepository.CreatePresenceSensor(createPresenceSensorRequest)

    async def PatchPresenceSensorData(self, patchPresenceSensorDataRequest: PatchPresenceSensorDataRequest) -> PatchPresenceSensorDataResponse:
        return await self._presenceSensorRepository.PatchPresenceSensorData(patchPresenceSensorDataRequest)