from abc import ABC, abstractmethod
from application.data_transfer_object.home_automation.sensor.temperature_sensor.create_temperature_sensor.CreateTemperatureSensorRequest import CreateTemperatureSensorRequest
from application.data_transfer_object.home_automation.sensor.temperature_sensor.create_temperature_sensor.CreateTemperatureSensorResponse import CreateTemperatureSensorResponse
from application.data_transfer_object.home_automation.sensor.temperature_sensor.patch_temperature_sensor.PatchTemperatureSensorRequest import PatchTemperatureSensorRequest
from application.data_transfer_object.home_automation.sensor.temperature_sensor.patch_temperature_sensor.PatchTemperatureSensorResponse import PatchTemperatureSensorResponse

class ITemperatureSensorApplication(ABC):

    @abstractmethod
    async def CreateTemperatureSensor(self, createTemperatureSensorRequest: CreateTemperatureSensorRequest) -> CreateTemperatureSensorResponse: ...

    @abstractmethod
    async def PatchTemperatureSensor(self, patchTemperatureSensorRequest: PatchTemperatureSensorRequest) -> PatchTemperatureSensorResponse: ...
